### PR TITLE
update blueprint with latest cli style

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by lukemelia** [comment]
Thanks, Kelly. Looks like this fails jshint, ironically enough.

**Comment by kellyselden** [comment]
Bummer. I didn't realize jshint was linting the blueprint files.

**Comment by duizendnegen** [comment]
I'll rebase tonight and merge if that works

**Comment by duizendnegen** [comment]
There you go @simonihmig - thanks for the initial contribution @kellyselden!

**Comment by simonihmig** [comment]
@duizendnegen cool, thanks!

_slightly off-topic: good to know you are still around and active w/ ember! Been a while, heard you left Hamburg because of TripRebel unfortunately declined. Still all the best! ;)_

**Pull request merged**
