### PR TITLE
better handling of "unavailablePlugins" error

### PR DESCRIPTION
**Pull request by ksnyde**

### CODE REVIEW

**Comment by lukemelia** [comment]
Thanks @ksnyde. Is it possible to get a test around this?

**Comment by ksnyde** [comment]
this was done to prevent the "Cannot convert object to primitive value" error people were getting in these issues:

- https://github.com/ember-cli-deploy/ember-cli-deploy/issues/397
- ember-cli-deploy/ember-cli-deploy-slack#13

**Comment by ksnyde** [comment]
@lukemelia yeah but not today ... sorry but need to prepare for a talk i'm doing tomorrow

**Comment by ksnyde** [comment]
I'm assuming the `node-tests/unit/tasks/pipeline-tests` is where to put this. Sorry but new to ember-cli-deploy so want to make sure I'm grokking it correctly.

**Comment by lukemelia** [comment]
@ksnyde yes, that would be the right file for the test. Thanks for your work on this.

**Comment by ghedamat** [comment]
@ksnyde this ended up being fixed in https://github.com/ember-cli-deploy/ember-cli-deploy/pull/405

sorry I didn't remember that you tackled it already!

if you want to open a PR to use `JSON.stringify` instead of the current solution I'm open to that, otherwise we can just leave it as is

thanks again for your help

**Pull request closed without merging**
