### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by lukemelia**
- [x] review
- [ ] merge
- [ ] tag as v1.0.0 and push
- [ ] npm publish
- [ ] 🍾

### CODE REVIEW

**Comment by ghedamat** [comment]
@lukemelia great work!

One thought:
I think we need to see if we can add a redirect rule from the beta docs to the stable ones

**Comment by lukemelia** [comment]
@ghedamat that would be cool. Do you have time to take a crack at it? https://help.github.com/articles/redirects-on-github-pages/ appears to have some info

**Comment by ghedamat** [comment]
@lukemelia sure, I'll try to push a commit here later today or tomorrow!

**Comment by ghedamat** [comment]
@lukemelia pushed

let me know what you think!

**Comment by lukemelia** [comment]
Looks good @ghedamat. Thanks for figuring that out!

**Comment by achambers** [comment]
You guys are awesome!

**Pull request merged**
