### PR TITLE
Add ember-cli-deploy-sftp to docs

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by lukemelia** [comment]
👍

**Comment by broerse** [comment]
@lukemelia the `ember-cli-deploy-sql` was not on  http://ember-cli-deploy.com/plugins/ ? Does this need some `gh-pages` deploy :smiley:

**Comment by lukemelia** [comment]
@broerse Thanks for that catch. We're deploying docs from master now, not gh-pages (i.e. https://github.com/ember-cli-deploy/ember-cli-deploy/blob/master/docs/plugins/index.md). Want to create a PR against master with the missing items?

**Comment by broerse** [comment]
@lukemelia Yes can do this this weekend.

**Comment by duizendnegen** [comment]
Can we close gh-pages then as well @lukemelia?

**Comment by broerse** [comment]
https://github.com/ember-cli-deploy/ember-cli-deploy/pull/471

I am also fore deleting the gh-pages branch.

**Comment by lukemelia** [comment]
Thanks Martin! Merged earlier and the `gh-pages` branch is no more!

**Pull request merged**
